config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    collection { post :import }
  end
  
  resources :comments
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

  get "login" => "sessions#new", :as => "login"
  post "create" => "sessions#create"
  get "logout" => "sessions#logout", :as => "logout"

  get "reset-password" => "sessions#reset_password", :as => "reset_password"
  post "find-reset-password" => "find_reset_password", :as => "find_reset_password"
  get "reset-password/:token/edit" => "sessions#reset_password_edit", :as => "reset_password_edit"
  post "reset-password-process/:token" => "sessions#reset_password_process", :as => "reset_password_process"
  get "download/:id" => "articles#download", :as => "download"

  root 'articles#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  def index
    @comments = Comment.page(params[:page]).per(15)
  end

  def new
    @comment = Comment.new
  end

  def create
    respond_to do |format|
      @comment = Comment.new(params_comment)
      if @comment.save
        format.js {@comments = Article.find_by_id(params[:comment][:article_id]).comments.order("id desc")}
      else
        format.js {@article = Article.find_by_id(params[:comment][:article_id])}
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(params_comment)
      flash[:notice] = "Success Update Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def destroy
    if @comment.destroy
      flash[:notice] = "Success Delete a Comments"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a comments"
      redirect_to action: 'index'
    end
  end

  def show

  end

  def edit

  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def params_comment
    params.require(:comment).permit(:article_id, :user_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div id="main-content">
  <%= form_for @comment, html: { multipart: true } do |f| %>

  <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content,  cols: 20, rows: 10, class: "form-control" %>
      <%= @comment.errors[:content].first unless @comment.errors[:content].blank? %>
    <br>
      <%= f.submit :submit, class: "btn btn-default" %>
    
  </div>
</div>
<% end %>


app/views/comments/create.js.erb
<% if @comment.errors.present? %>
        $("#form-comment").html(" <%= j( render 'articles/form' ) %>");
    $($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");
        <% else %>
            $("#list-comments").html(" <%= j( render 'articles/comments' ) %>");
            $("#comment_content").val('');
            $("div.field_with_errors p.message").remove();
    <% end %>

app/views/comments/edit.html.erb
<div class= "container">
  <h3>Edit Comment </h3>
  <div id="main-content">
    <%= render 'form' %>
  </div>
  <div>
    <%= link_to "back to index", comments_path %>
  </div>
</div>

app/views/comments/index.html.erb
<div class="container">
  <% @comments.each do |comment| %>
  <p>
    <%= comment.content %>
    <hr>
  </p>
  <div class="comment" id="<%= comment.id %>">
    <span><%= link_to 'Edit', edit_comment_path(comment.id), class: "btn btn-primary" %> </span>
    <span><%= link_to 'Delete', comment_path(comment.id), class: "btn btn-primary", method: "DELETE", data: {confirm: 'Delete this data ? '} %> </span>
  <hr />
  </div>
  <% end %>
  <center>
  <%= link_to 'New Comment', new_comment_path, class:"btn btn-new-article" %>
  </center>
</div>

app/views/comments/new.html.erb
<div class= "container">
  <h3>New Comment </h3>
  <%= render 'form' %>
</div>