config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    collection { post :import }
  end
  
  resources :comments
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

  get "login" => "sessions#new", :as => "login"
  post "create" => "sessions#create"
  get "logout" => "sessions#logout", :as => "logout"

  get "reset-password" => "sessions#reset_password", :as => "reset_password"
  post "find-reset-password" => "find_reset_password", :as => "find_reset_password"
  get "reset-password/:token/edit" => "sessions#reset_password_edit", :as => "reset_password_edit"
  post "reset-password-process/:token" => "sessions#reset_password_process", :as => "reset_password_process"
  get "download/:id" => "articles#download", :as => "download"

  root 'articles#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 10 }
  
  def self.import(file)

    spreadsheet = open_spreadsheet(file)

    page_article = spreadsheet.sheet('Article')
    (2..page_article.last_row).each do |no_row|
      @article =
      article_new = Article.new
      article_new.title = page_article.row(no_row)[0]
      article_new.content = page_article.row(no_row)[1]
      article_new.save(validate:false)
    end

    page_comment = spreadsheet.sheet('Comments')
    (2..page_comment.last_row).each do |no_row|
      @comments = Comment.create(
       article_id: @article.id,
       user_id: page_comment.row(no_row)[0],
     content: page_comment.row(no_row)[1])
    end
  end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when '.csv' then Csv.new(file.path, nil, :ignore)
  when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
  when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]
  def index
    @articles = Article.page(params[:page]).per(10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params_article)
    if @article.save
      flash[:notice] = "Success Add Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'new'
    end
  end

  def update
    @article = Article.find_by_id(params[:id])
    if @article.update(params_article)
      flash[:notice] = "Success Update Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])
    if @article.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end
  end

  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

  def download
    @article = Article.all
    @comments = Article.find_by_id(params[:id]).comments
    respond_to do | format |
      format.xlsx { response.headers['Content-Disposition'] = 'attachment; filename="articles.xlsx"' }
    end
  end

  def import
    Article.import(params[:file])
    redirect_to root_url, notice: "Articles imported."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def params_article
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article" id="<%= article.id %>">
  <div class="front">
    <%= link_to article, class: 'pic-link' do %>
      <%= image_tag article.image.url(:square) %>
    <% end %>
  </div>

  <div class="back">
    <span class="article-name"><%= article.name %></span>
    <div class="actions">
      <%= link_to 'Show', article %>
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Delete', article, confirm: 'Are you sure you want to lose a friend?', method: :delete, class: 'destroy' %>
    </div>
  </div>
</div>

app/views/articles/_comments.html.erb
<div class="container">
  <hr>
  <% @comments.each do |comment| %>
  <p>
    <i><%= comment.content %></i>
<hr />
  </p>
  <% end %>
</div>
<hr />
</div>

app/views/articles/_form.html.erb
<div id="main-content">
  <%= form_for @article, html: { multipart: true } do |f| %>
  <div class="form-group">  
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
      <%= @article.errors[:title].first unless @article.errors[:title].blank? %>
    <br>
      <%= f.label :content %>
      <%= f.text_area :content,  cols: 20, rows: 10, class: "form-control" %>
      <%= @article.errors[:content].first unless @article.errors[:content].blank? %>
    <br>
      <%= f.submit :submit, class: "btn btn-default" %>
  </div>
</div>
<% end %>


app/views/articles/_form_comment.html.erb
 <%= form_for @comment, url: comments_path, remote: true do |f| %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <br/>
        <%= f.label :content %>
        <%= f.text_area :content, class: "comment", cols: 20, rows: 5, placeholder: "Enter your comment" %>
        <br/>
        <% if !current_user %>
            <%= link_to 'Log-In', login_path, class: "btn btn-primary" %>
            <% else %>
            <%= f.submit :submit, class: "btn btn-primary" %>
            <% end %>
        
    <% end %>

app/views/articles/edit.html.erb
<div class= "container">
  <h3>Edit Article </h3>
  <div id="main-content">
    <%= render 'form' %>
  </div>
  <div>
    <%= link_to "back to index", articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <br>
  <br>

  <%= form_tag import_articles_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
  <% end %>
    
  <div class="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 50 }'>
    <div class="grid">

      <% @articles.each do |article| %>
      <div class="grid-item">
        
        <h3><%= article.title %></h3>
        <p>
          <%= article.content.truncate(100) %>
          <%= link_to 'Read more', article_path(article.id) %>
        </p>
        <div class="article" id="<%= article.id %>">
          <div class="front">
            <p>
              <span><%= link_to 'Edit', edit_article_path(article.id), class: "btn btn-primary" %> </span>
              <span><%= link_to 'Delete', article_path(article.id), class: "btn btn-primary", method: "DELETE", data: {confirm: 'Delete this data ? '} %> </span>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class= "container">
  <h3>New Article </h3>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
<!-- <p id="notice">
  <%= notice%>
</p> -->
<p>
  <h3><%= @article.title %></h3>
<p>
  <%= @article.content %>
</p>
<p>
  <%= link_to 'Back to Index', articles_path, class: "btn btn-default" %>
  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-default" %>
  <%= link_to 'Export', download_path(format: :xlsx), class: "btn btn-default" %>
</p>
<hr />
<div id="form-comment">
        <%= render 'form_comment' %>
    </div>

 <h4><b>Here the comments</b></h4>

    <div id="list-comments">
        <%= render 'comments' %>
    </div>
</div>