config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    collection { post :import }
  end
  
  resources :comments
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

  get "login" => "sessions#new", :as => "login"
  post "create" => "sessions#create"
  get "logout" => "sessions#logout", :as => "logout"

  get "reset-password" => "sessions#reset_password", :as => "reset_password"
  post "find-reset-password" => "find_reset_password", :as => "find_reset_password"
  get "reset-password/:token/edit" => "sessions#reset_password_edit", :as => "reset_password_edit"
  post "reset-password-process/:token" => "sessions#reset_password_process", :as => "reset_password_process"
  get "download/:id" => "articles#download", :as => "download"

  root 'articles#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task5</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="padding-top:60px;">
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <h4 class = "navbar-brand">Make new article <%= link_to 'New Article', new_article_path, class:"btn btn-new-article" %></h4>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><% if !current_user %>
            <%= link_to 'Log-In', login_path %></li>
            <li><%= link_to 'Sign-Up', sign_up_path %></li>
            <% else %>
            <li>Hello <%= current_user.username %></li>
            <li><%= link_to 'Log-Out', logout_path(current_user.id) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>